version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: weatherservice-postgres
    restart: always
    environment:
      POSTGRES_DB: weatherapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: weatherapp123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: weatherservice-redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    image: weatherservice-backend:1.0
    container_name: weatherservice-backend
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  frontend:
    build: ./frontend
    image: weatherservice-frontend:1.0
    container_name: weatherservice-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  postgres_data: