spring.application.name=WeatherService
systemApiKey = premium-4fde29ef-1676466811

# Liquibase Configuration
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

# API
weather.api.url=https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline
weather.api.key=DRPWCRSU9WQQDD5XLY7RJYPQQ

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/weatherapp
spring.datasource.username=postgres
spring.datasource.password=weatherapp123

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=1000ms

#Yandex
spring.mail.host=smtp.yandex.ru
spring.mail.port=465
spring.mail.protocol=smtps
spring.mail.username=weather.service@yandex.ru
spring.mail.password=mmlnkptywykwmhop

#?????? ???????? ?? ???????
weather.limits.free=10
weather.limits.basic=100
weather.limits.premium=-1

#???? ?? ???????? ? ??????
payment.price.basic=500
payment.price.premium=1000

#?????? ???????? ??????????????
weather.alert.heat-threshold=30
weather.alert.cold-threshold=-20
weather.alert.wind-threshold=15

#????? ????? ? ???????
payment.expire-minutes=15
password.reset.expire-minutes=15

#??? ? ???????
redis.cache.ttl-minutes=15

#??????? ?????? ??? ????????????? ???????
payment.success-probability=0.8